config/routes.rb
Rails.application.routes.draw do
  get 'submissions/report'
  get 'submissions/all'
  get 'submissions/user_report'
  get 'submissions/final_decisions_report'
  post 'submissions/report'

  resources :reviewer_assignments
  resources :submission_reviews
  resources :conferences
  devise_for :users
  resources :submissions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'submissions#index'
end

app/models/submission.rb
class Submission < ApplicationRecord
    attr_accessor :reviewers
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  include ApplicationHelper
  include SubmissionsHelper
  before_action :authenticate_user!
  before_action :set_submission, only: [:show, :edit, :update, :destroy]

  # GET /submissions
  # GET /submissions.json
  def index

    @submissions = []
    @should_show_admin_data = false

    get_submissions_assigned_to(current_user.id, @submissions)

    # fills in the data tables for each proposal
    get_data_for_each_proposal(current_user.id, @submissions, false)
    
  end

  # GET /submissions/all
  # GET /submissions/all.json
  def all
    only_admins()
    @should_show_admin_data = true
    # get all submissions
    @submissions = Submission.all
    # fills in the data tables for each proposal
    get_data_for_each_proposal(current_user.id, @submissions, true)
  end

  # GET /submissions/1
  # GET /submissions/1.json
  def show
    # Review this user has submitted
    @user_submitted_review = SubmissionReview.where('(submission_id= ? AND reviewer_id= ?)', @submission.id, current_user.id)
    
    # Users assigned to review this report
    @reviewers = ReviewerAssignment.where(submission_id: @submission.id)
    @submission_reviews = SubmissionReview.where(submission_id: @submission.id, final: false)
    @submission_reviews.each do |review|
      review.reviewer_email = User.find(review.reviewer_id).name
    end

    # potential new review
    @submission_review = SubmissionReview.new
    
    # get final decision or create new review for it
    final_decision_reviews = SubmissionReview.where(submission_id: @submission.id, final: true)
    if final_decision_reviews.length == 0
      @final_decision_submission_review = SubmissionReview.new
    else
      @final_decision_submission_review = final_decision_reviews[0]
    end

    # Get conference name for this Submission
    @conference_name = Conference.find(@submission.conference_id).name

    # get data for submission
    @submissions = [@submission]
    get_data_for_each_proposal(current_user.id, @submissions, true)
  end

  # GET /submissions/new
  def new
    @submission = Submission.new
    @conferences = Conference.all
  end

  # GET /submissions/1/edit
  def edit
    @conferences = Conference.all
  end

  # POST /submissions
  # POST /submissions.json
  def create
    @submission = Submission.new(submission_params)
    respond_to do |format|
      if @submission.save
        format.html { redirect_to @submission, notice: 'Submission proposal was successfully created.' }
        format.json { render :show, status: :created, location: @submission }
      else
        format.html { render :new }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /submissions/1
  # PATCH/PUT /submissions/1.json
  def update
    respond_to do |format|
      if @submission.update(submission_params)
        format.html { redirect_to @submission, notice: 'Submission proposal was successfully updated.' }
        format.json { render :show, status: :ok, location: @submission }
      else
        format.html { render :edit }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submissions/1
  # DELETE /submissions/1.json
  def destroy
    @submission.destroy
    respond_to do |format|
      format.html { redirect_to submissions_url, notice: 'Submission proposal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def report
    only_admins()

    # get table data
    reviewerAssignments = ReviewerAssignment.all
    submissions = Submission.all

    # data collection
    # [reviews completed, total assigned reviews]
    @lazy_users = Hash.new
    @submission_counts = [[], [], [], [], [], [], []]
    @review_percents = [[], [], [], [], [], [], []]
    @final_decision_counts = [[], [], [], []]

    # get all users who haven't submitted their reviews
    reviewerAssignments.each do |assignment|
      review = SubmissionReview.where(submission_id: assignment.submission_id, reviewer_id: assignment.user_id)
      user = User.find(assignment.user_id)

      # add to total reviewerAssignment count
      if @lazy_users[user.email] == nil
        @lazy_users[user.email] = Hash.new
        @lazy_users[user.email]["completed"] = 0 
        @lazy_users[user.email]["assigned"] = 1
        @lazy_users[user.email]["user_id"] = user.id 
      else
        @lazy_users[user.email]["assigned"] += 1
      end

      # add to completed reviews
      if review.length != 0
          @lazy_users[user.email]["completed"] += 1
      end
    end

    # get percentages for every user and add user_id to array
    @lazy_users.each do |key, review_data|
      perc = to_percent(review_data["completed"], review_data["assigned"])
      tier = get_tier_from_percentage(perc)
      @review_percents[tier].push(review_data["user_id"])
    end

    # get all submission review data 
    submissions.each do |submission|
      reviews = SubmissionReview.where(submission_id: submission.id)
      final_reviews = SubmissionReview.where(submission_id: submission.id, final: true)
      if (@submission_counts[reviews.length])
        @submission_counts[reviews.length].push(submission)
      end
      # add all final reviews to count
      if final_reviews.length > 0
        review = final_reviews[0]
        @final_decision_counts[review.recommendation].push(review)
      end
    end

  end

  def user_report
    @submissions = []
    get_submissions_assigned_to(params[:report_user_id], @submissions)
    # fills in the data tables for each proposal
    get_data_for_each_proposal(params[:report_user_id], @submissions, false)
  end

  def final_decisions_report
    @final_decision_reviews = []
    @emails = ""
    params[:final_decision_reviews].each_with_index do |review_id, index|
      submission_review = SubmissionReview.find(review_id)
      submission_review.submission = Submission.find(submission_review.submission_id)
      submission_review.submission.reviewers = []
      # create email string
      @emails += submission_review.submission.contact_email
      if index != params[:final_decision_reviews].length - 1
        @emails += ", "
      end
      # add reviewers emails
      reviews = SubmissionReview.where(submission_id: submission_review.submission.id)
      reviews.each do |review|
        reviewer = User.find(review.reviewer_id)
        submission_review.submission.reviewers.push(reviewer.email)
      end
      submission_review.submission.reviewers = submission_review.submission.reviewers.uniq

      @final_decision_reviews.push(submission_review)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submission
      @submission = Submission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def submission_params
      params.require(:submission).permit(:title, :url, :contact_name, :contact_email, :organization, :proposed_format, :conference_id)
    end

    def get_submissions_assigned_to(report_user_id, array)
      ReviewerAssignment.where(user_id: report_user_id).each do |assignment|
        array.push(Submission.find(assignment.submission_id))
      end
    end
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
    include ApplicationHelper
    def get_data_for_each_proposal(report_user_id, submissions, is_admin)
      # arrays for data for each proposal
      @reviews_percent = []
      @reviews_completed = []
      @assigned_reviewers = []
      @innovation = []
      @breadth = []
      @quality = []
      @recommendation = []
      @final_decisions = []

      # Get data for each proposal
      submissions.each do |submission|

        # if the user is not an admin, just get the data for their report
        if is_admin == false
            review = SubmissionReview.where(submission_id: submission.id, reviewer_id: report_user_id)
            # if the user has submitted a review
            if review.length > 0
                @innovation.push(review[0].innovation)
                @breadth.push(review[0].breadth)
                @quality.push(review[0].presentation_quality)
                @recommendation.push(review[0].recommendation)
            else
                @innovation.push("")
                @breadth.push("")
                @quality.push("")
                @recommendation.push(4)
            end
            next
        end

        # if the user IS an admin, get the data for all reviews
        reviews = SubmissionReview.where(submission_id: submission.id, conflict_of_interest: false, final: false)
        final_reviews = SubmissionReview.where(submission_id: submission.id, final: true)
        reviewers = ReviewerAssignment.where(submission_id: submission.id)
        
        @assigned_reviewers.push(reviewers.length)

        if final_reviews.length == 0
          @final_decisions.push("No Decision")
        else
          final_review = final_reviews[0]
          @final_decisions.push(recommendation_options_choice[final_review.recommendation][0])
        end

        if reviews.length == 0 # if there are no reviews
          # nothing to calculate
          @reviews_completed.push(0)
          @innovation.push(0)
          @breadth.push(0)
          @quality.push(0)
          @recommendation.push(0)
          @reviews_percent.push(0)
        else # if there is at least 1 review
          @reviews_percent.push(to_percent(reviews.length, reviewers.length))
          @reviews_completed.push(reviews.length)

          # get data for averages
          i = b = q = r = 0
          reviews.each do |review|
            if review.conflict_of_interest || review.final
              next
            end
            i += review.innovation
            b += review.breadth
            q += review.presentation_quality
            r += review.recommendation
          end

          @innovation.push( average(i, reviews.length) )
          @breadth.push( average(b, reviews.length) )
          @quality.push( average(q, reviews.length) )
          @recommendation.push( average(r, reviews.length) )
        end

      end
    end

    def get_tier_from_percentage(perc)
      case
        when perc == 0.0
          return 0
        when perc > 0.0 && perc < 20.0
          return 1
        when perc >= 20.0 && perc < 40.0
          return 2
        when perc >= 40.0 && perc < 60.0
          return 3
        when perc >= 60.0 && perc < 80.0
          return 4
        when perc >= 80.0 && perc < 100.0
          return 5
        when perc == 100
          return 6
      end
    end
end

app/views/submissions/_form.html.erb
<%
  conferenceOptions = []
  for conf in @conferences do
    conferenceOptions.push([conf.name, conf.id])
  end
%>

<%= form_with(model: submission, local: true) do |form| %>
  <% if submission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(submission.errors.count, "error") %> prohibited this submission from being saved:</h2>

      <ul>
      <% submission.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :submission_title %>
  </div>

  <div class="field">
    <%= form.label :conference_id %>
    <%= form.select :conference_id, conferenceOptions %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :submission_url %>
  </div>

  <div class="field">
    <%= form.label :contact_name %>
    <%= form.text_field :contact_name, id: :submission_contact_name %>
  </div>

  <div class="field">
    <%= form.label :contact_email %>
    <%= form.text_field :contact_email, id: :submission_contact_email %>
  </div>

  <div class="field">
    <%= form.label :organization %>
    <%= form.text_field :organization, id: :submission_organization %>
  </div>

  <div class="field">
    <%= form.label :proposed_format %>
    <%= form.text_field :proposed_format, id: :submission_proposed_format %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/submissions/_submissions_table.html.erb
<table id="reviews-table" class="table table-hover table-striped" cellspacing="0" width="100%">

    <thead>

        <tr>
        <th scope="col">Title</th>
        <% if is_admin?(current_user) && @should_show_admin_data then %>
            <th scope="col"> Progress </th>
            <th scope="col"> Reviews </th>
            <th scope="col"> Max </th>
        <% end %>

        <th scope="col"> Innovation </th>
        <th scope="col"> Breadth </th>
        <th scope="col"> Quality </th>
        <th scope="col"> Rec. Score </th>
        <th scope="col"> Recommendation </th>
        
        <% if is_admin?(current_user) && @should_show_admin_data then %>
            <th scope="col"> Final Decision </th>
            <th scope="col" colspan="1">  </th>
        <% end %>
        </tr>

    </thead>

    <tbody>
        <% i = 0 %>
        <% @submissions.each do |submission| %>
            <tr class="row-proposal" onclick="window.location='/submissions/<%= submission.id %>'">
            <td scope="row"><%= submission.title %></td>

            
            <% if is_admin?(current_user) && @should_show_admin_data then %>
                <td scope="row"><%= @reviews_percent[i] %>%</td>
                <td scope="row"><%= @reviews_completed[i] %></td>
                <td scope="row"><%= @assigned_reviewers[i] %></td>
            <% end %>  

            <td scope="row"><%= @innovation[i] %></td>
            <td scope="row"><%= @breadth[i] %></td>
            <td scope="row"><%= @quality[i] %></td>
            <td scope="row"><%= @recommendation[i] %></td>
            <% if @reviews_completed[i] == 0 %>
                <td scope="row"><%= recommendation_options_display[4][0] %></td>
            <% else %>
                <td scope="row"><%= recommendation_options_display[(@recommendation[i]+0.5)][0] %></td>
            <% end %>

            <% if is_admin?(current_user) && @should_show_admin_data then %>
                <td scope="row"><%= @final_decisions[i] %></td>
                <td><%= link_to 'Show', submission_path(submission) %></td>
            <% end %>

            </tr>
            <% i += 1 %>
        <% end %>
    </tbody>
</table>

<script>

    $('.dataTables_filter').addClass('pull-left');
</script>

<% if @should_show_admin_data %>
    <script>
        $(document).ready(function() {
            $('#reviews-table').DataTable({
                scrollY: 500,
                "dom":' <"search"f><"top"l>rt<"bottom"ip><"clear">',
                "iDisplayLength": -1,
                "aLengthMenu": [[25, 50, 100, -1], [25, 50, 100, "All"]],
                "order": [7, "desc"]
            });
        });
    </script>
<% else %>
<script>
        $(document).ready(function() {
            $('#reviews-table').DataTable({
                scrollY: 500,
                "dom":' <"search"f><"top"l>rt<"bottom"ip><"clear">',
                "iDisplayLength": 25,
                "aLengthMenu": [[25, 50, 100, -1], [25, 50, 100, "All"]],
                "order": [4, "desc"]
            });
        });
    </script>
<% end %>

app/views/submissions/all.html.erb
</br>

<div class="center">
    <h1>All Submissions</h1>
</div>

</br>

<%= render 'submissions_table' %>

app/views/submissions/edit.html.erb
<h1>Editing Submission</h1>

<%= render 'form', submission: @submission %>

<%= link_to 'Show', @submission %> |
<%= link_to 'Back', submissions_path %>

app/views/submissions/final_decisions_report.html.erb
</br>

<div class="center">
    <h1><b><%= params[:recommendation] %></b> Submissions</h1>
</div>

</br>

<button class="btn btn-sm btn-outline-primary" onclick="copyToClipboard('<%= @emails %>')">Copy All Contact Emails <i class="fa fa-clipboard" aria-hidden="true"></i></button>

</br>
</br>

<table class="table table-hover table-striped">
    <thead>
        <tr>
            <th scope="col">Title</th>
            <th scope="col">Contact Name</th>
            <th scope="col">Contact Email</th>
            <th scope="col">Organization</th>
        </tr>
    </thead>

    <tbody>
        <% @final_decision_reviews.each do |review| %>
            <tr class="row-proposal" onclick="window.location='/submissions/<%= review.submission.id %>'">
                <td><%= review.submission.title %></td>
                <td><%= review.submission.contact_name %></td>
                <td><%= review.submission.contact_email %></td>
                <td><%= review.submission.organization %></td>
            </tr>
        <% end %>
    </tbody>
</table>

<script>
    function copyToClipboard(text) {
        var $temp = $("<input>");
        $("body").append($temp);
        $temp.val(text).select();
        document.execCommand("copy");
        $temp.remove();
        console.log(text)
    }
</script>

app/views/submissions/index.html.erb
</br>

<div class="center">
    <h1>Assigned Submissions</h1>
</div>

</br>

<%= render 'submissions_table' %>

<br>

app/views/submissions/new.html.erb
<h1>New Submission</h1>

<%= render 'form', submission: @submission %>

<%= link_to 'Back', submissions_path %>

app/views/submissions/report.html.erb
</br>

<div class="center">
    <h1>Admin Report</h1>
</div>

</br>
<h5> Reports sorted by review completion </h5>
</br>

<div class="boxed">
    <table class="table">
        <thead>
            <tr>
                <th>Reviews Completed</th>
                <th>Submissions</th>
            </tr>
        </thead>
        <tbody>
            <% i = @submission_counts.length-1 %>
            <% until i < 0 do %>
                <tr>
                    <td><%= i %></td>
                    <td><%= @submission_counts[i].length %></td>
                </tr>
                <% i -= 1 %>
            <% end %>
        </tbody>
    </table>
</div>

</br>

</br>
<h5> User Review Completion </h5>
</br>

<div class="boxed">
        <table class="table">
            <thead>
                <tr>
                    <th>Progress</th>
                    <th>User Count</th>
                </tr>
            </thead>
            <tbody>
                <% i = @review_percents.length-1 %>
                <% until i < 0 do %>
                    <tr>
                        <td><%= progress_labels[i] %></td>
                        <td><%= @review_percents[i].length %></td>
                    </tr>
                    <% i -= 1 %>
                <% end %>
            </tbody>
        </table>
</div>

</br>

</br>
<h5> Final Decisions </h5>
</br>

<div class="boxed">
        <table class="table">
            <thead>
                <tr>
                    <th>Decision</th>
                    <th>Count</th>
                </tr>
            </thead>
            <tbody>
                <% i = @final_decision_counts.length-1 %>
                <% until i < 0 do %>
                    <tr>
                        <td><%= recommendation_options_choice[i][0] %></td>
                        <td>
                            <%= link_to @final_decision_counts[i].length, {:controller => "submissions", :action => "final_decisions_report", :recommendation => recommendation_options_choice[i][0], :final_decision_reviews => @final_decision_counts[i] } %>
                        </td>
                    </tr>
                    <% i -= 1 %>
                <% end %>
            </tbody>
        </table>
</div>

</br>

<h5> Users who still need to complete reports</h5>
<hr>
[email, reviews remaining, %complete]
<% @lazy_users.each do |key, value| %>
    <div>
        [<%= key %>, <%= (value["assigned"]-value["completed"]) %> reviews left, <%= link_to to_percent(value["completed"], value["assigned"]).to_s + "%", {:controller => "submissions", :action => "user_report", :report_user_id => value["user_id"], :user_email => key } %> complete]
    </div>
<% end %>

</br>
</br>
</br>

app/views/submissions/show.html.erb
</br>

<div class="center">
  <h3><strong>Submission</strong><h3>
</div>

</br>

<div class="boxed"> 
  <p>
    <strong>Title:</strong>
    <%= @submission.title %>
  </p>

  <p>
    <strong>Conference:</strong>
    <%= @conference_name %>
  </p>

  <p>
    <strong>Url:</strong>
    <a href="<%=@submission.url%>"><%= @submission.url %></a>
  </p>

  <% if is_admin?(current_user) %>
    <p>
      <strong>Contact Name:</strong>
      <%= @submission.contact_name %>
    </p>

    <p>
      <strong>Contact Email:</strong>
      <%= @submission.contact_email %>
    </p>

    <p>
      <strong>Organization:</strong>
      <%= @submission.organization %>
    </p>
  <% end %>

  <p>
    <strong>Proposed Format:</strong>
    <%= @submission.proposed_format %>
  </p>

  <% if is_admin?(current_user) %>
    <form action="<%= edit_submission_path(@submission) %>">
      <button type="submit" class="btn btn-outline-success">Edit</button>  
    </form>
  <% end %>

</div>

</br>

<% if is_admin?(current_user) %>
  <div class="center">
      <h3><strong>Final Decision</strong><h3>
    </div>
    
    </br>

    <div class="boxed"> 
      </br>
      <%= render '/submission_reviews/form', submission_review: @final_decision_submission_review, is_final: true, minimal: true %>
    </div>
<% end %>

</br>

<div class="center">
  <h3><strong>Average Review Scores</strong><h3>
</div>


<div class="boxed">
  <table id="reviews-table" class="table table-hover table-striped" cellspacing="0" width="100%">

      <thead>
          <tr>
          <th scope="col">Title</th>
          <th scope="col"> Review Progress </th>
          <th scope="col"> Completed Reviews </th>
          <th scope="col"> Max Reviews </th>

          <th scope="col"> Innovation </th>
          <th scope="col"> Breadth </th>
          <th scope="col"> Quality </th>
          <th scope="col"> Rec. Score </th>
          <th scope="col"> Recommendation </th>
        
          </tr>

      </thead>

      <tbody>
          <% i = 0 %>
          <% @submissions.each do |submission| %>
              <tr class="row-proposal" onclick="window.location='/submissions/<%= submission.id %>'">
              <td scope="row"><%= submission.title %></td>

              
              <td scope="row"><%= @reviews_percent[i] %>%</td>
              <td scope="row"><%= @reviews_completed[i] %></td>
              <td scope="row"><%= @assigned_reviewers[i] %></td>

              <td scope="row"><%= @innovation[i] %></td>
              <td scope="row"><%= @breadth[i] %></td>
              <td scope="row"><%= @quality[i] %></td>
              <td scope="row"><%= @recommendation[i] %></td>
              <td scope="row"><%= recommendation_options_display[(@recommendation[i]+0.5)][0] %></td>

    
              </tr>
              <% i += 1 %>
          <% end %>
      </tbody>
  </table>
</div>

</br>
  <div class="center">
    <h3><strong>Reviews</strong><h3>
  </div>

  
  <div class="boxed">

      <%= render '/submission_reviews/index' %>
  </div>

</br>

<% if is_admin?(current_user) %> 
  <div class="center">
    <h3><strong>Reviewers</strong><h3>
  </div>
  
  <div class="boxed">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Email</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% for reviewer in @reviewers do %>
          <tr>
            <td><%= User.find(reviewer.user_id).email %></td>
            <td class="align-right"><%= button_to 'Remove Reviewer', reviewer, class: "btn btn-sm btn-outline-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>  
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= render '/reviewer_assignments/form', reviewer_assignment: ReviewerAssignment.new, submission_id: @submission.id %>

  </div>
<% end %>

</br>

<% if @user_submitted_review.length >= 1 then %>
  
  <div class="center">
    <h3><strong>Your Review</strong><h3>
  </div>

  </br>

  <div class="boxed"> 

    </br>

    <% @submission_review = @user_submitted_review[0] %>
    <%= render '/submission_reviews/form', submission_review: @submission_review, is_final: false, minimal: false %>
  </div>
<% else %>
  <div class="center">
    <h3><strong>Review</strong><h3>
  </div>
  
  </br>

  <div class="boxed"> 
    </br>

    <%= render '/submission_reviews/form', submission_review: @submission_review, is_final: false, minimal: false %>
  </div>
<% end %>

</br>

app/views/submissions/user_report.erb
</br>

<div class="center">
    <h1>Reviews from <%= params[:user_email]%></h1>
</div>

</br>

<%= render 'submissions_table' %>

<%= button_to "Back", :back, :class => "btn btn-primary", :method => :get %>