config/routes.rb
Rails.application.routes.draw do
  get 'submissions/report'
  get 'submissions/all'
  get 'submissions/user_report'
  get 'submissions/final_decisions_report'
  post 'submissions/report'

  resources :reviewer_assignments
  resources :submission_reviews
  resources :conferences
  devise_for :users
  resources :submissions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'submissions#index'
end

app/controllers/submission_reviews_controller.rb
class SubmissionReviewsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_submission_review, only: [:show, :edit, :update, :destroy]

  # GET /submission_reviews
  # GET /submission_reviews.json
  def index
    @submission_reviews = SubmissionReview.all
  end

  # GET /submission_reviews/1
  # GET /submission_reviews/1.json
  def show
  end

  # GET /submission_reviews/new
  def new
    @submission_review = SubmissionReview.new
  end

  # GET /submission_reviews/1/edit
  def edit
  end

  # POST /submission_reviews
  # POST /submission_reviews.json
  def create
    @submission_review = SubmissionReview.new(submission_review_params)

    respond_to do |format|
      if @submission_review.save
        submission = Submission.find(@submission_review.submission_id)
        if @submission_review.final
          format.html { redirect_to "/submissions/all", notice: 'Submission review was successfully updated.' }
        else
          format.html { redirect_to "/", notice: 'Submission review was successfully updated.' }
        end        # format.json { render :show, status: :created, location: @abstract_report }
      else
        format.html { render :new }
        format.json { render json: @submission_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /submission_reviews/1
  # PATCH/PUT /submission_reviews/1.json
  def update
    respond_to do |format|
      if @submission_review.update(submission_review_params)
        if @submission_review.final
          format.html { redirect_to "/submissions/all", notice: 'Submission review was successfully updated.' }
        else
          format.html { redirect_to "/", notice: 'Submission review was successfully updated.' }
        end
      else
        format.html { render :edit }
        format.json { render json: @submission_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submission_reviews/1
  # DELETE /submission_reviews/1.json
  def destroy
    @submission_review.destroy
    respond_to do |format|
      format.html { redirect_to submissions_url, notice: 'Submission review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submission_review
      @submission_review = SubmissionReview.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def submission_review_params
      params.require(:submission_review).permit(:submission_id, :reviewer_id, :recommendation, :innovation, :breadth, :presentation_quality, :public_content, :conflict_of_interest, :notes, :final)
    end
end

app/helpers/submission_reviews_helper.rb
module SubmissionReviewsHelper
end

app/views/submission_reviews/_form.html.erb
<%= form_with(model: submission_review, local: true) do |form| %>
  <% if submission_review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(submission_review.errors.count, "error") %> prohibited this submission_review from being saved:</h2>

      <ul>
      <% submission_review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <% if @submission != nil then %>
      <%= form.hidden_field :submission_id, value: @submission.id %>
      <%= form.hidden_field :reviewer_id, value: current_user.id %>
  <% end %>
  <%= form.hidden_field :final, value: is_final %>
  <table class="table">
      
      <tbody>
          <% if !minimal %>
            <tr>
              <td> Conflict of Interest </td>
              <td> <%= form.check_box :conflict_of_interest %> </td>
            </tr>
            <tr>
              <td> Innovation </td>
              <td> <%= form.select(:innovation, innovation_options, {}, {:class => "form-control"}) %> </td>
            </tr>
            <tr>
              <td> Breadth </td>
              <td> <%= form.select(:breadth, breadth_options, {}, {:class => "form-control"}) %> </td>
            </tr>
            <tr>
              <td> Presentation Quality </td>
              <td> <%= form.select(:presentation_quality, presentation_quality_options, {}, {:class => "form-control"}) %> </td>
            </tr>
            <tr>
              <td> Content could be presented publicly/externally </td>
              <td> <%= form.check_box :public_content %> </td>
            </tr>
          <% end %>
          <tr>
            <td> Notes </td>
            <td> <%= form.text_area(:notes, class: "form-control") %> </td>
          </tr>
          <tr>
            <td> Overall Recommendation </td>
            <td> <%= form.select(:recommendation, recommendation_options_choice, {}, {:class => "form-control"}) %> </td>
          </tr>
      </tbody>
  </table>

  </br>

  <div class="center">
    <div class="actions">
      <% if is_final %>
        <%= form.submit "Submit Final Decision", class: "btn btn-success" %>
      <% else %>
        <%= form.submit "Submit Review", class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/submission_reviews/_index.html.erb
<table class="table table-striped">

  <thead>
    <tr>
      <th>User</th>
      <th>Conflict</th>
      <th>Public</th>
      <th>Innovation</th>
      <th>Breadth</th>
      <th>Quality</th>
      <th>Rec. Score</th>
      <th>Recommendation</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @submission_reviews.each do |submission_review| %>
      <tr>
        <td><%= submission_review.reviewer_email %></td>
        <td><%= submission_review.conflict_of_interest %></td>
        <td><%= submission_review.public_content %></td>
        <td><%= submission_review.innovation %></td>
        <td><%= submission_review.breadth %></td>
        <td><%= submission_review.presentation_quality %></td>
        <td><%= submission_review.recommendation %></td>
        <td><%= recommendation_options_display[submission_review.recommendation][0] %></td>
        <td><% link_to 'Show', submission_review %></td>
        <td><% link_to 'Edit', edit_submission_review_path(submission_review) %></td>
        <td><% link_to 'Destroy', submission_review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <tr>
        <td></td>
        <td colspan="9"><strong>Notes:</strong> <%= submission_review.notes %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/submission_reviews/_show.html.erb
<p>
  <strong>Conflict of Interest/Not Enough Expertise to Review:</strong>
  <%= @submission_review.conflict_of_interest %>
</p>
<br>



<p>
  <strong>Innovation:</strong>
  <%= innovation_options[@submission_review.innovation] %>
</p>

<p>
  <strong>Breadth:</strong>
  <%= breadth_options[@submission_review.breadth] %>
</p>

<p>
  <strong>Presentation Quality:</strong>
  <%= presentation_quality_options[@submission_review.presentation_quality] %>
</p>

<p>
  <strong>Public Content:</strong>
  <%= @submission_review.public_content %>
</p>


<br>
<p>
  <strong>Notes:</strong>
  <%= @submission_review.notes %>
</p>

<br>

 <strong>Recommendation:</strong>
  <%= recommendation_options_display[@submission_review.recommendation] %>
</p>




<% if current_user.id == @submission_review.reviewer_id then %>
  <form action="<%= edit_submission_review_path(@submission_review) %>">
    <button type="submit" class="btn btn-outline-success">Edit</button>  
  </form>
<% end %>

app/views/submission_reviews/edit.html.erb
</br>

<div class="boxed">
    <h1>Editing Review</h1>
    
    </br>

    <%= render 'form', submission_review: @submission_review %>        
</div>

app/views/submission_reviews/new.html.erb
<h1>New Abstract Report</h1>

<%= render 'form', submission_review: @submission_review %>

<%= link_to 'Back', submission_reviews_path %>